Resources:
  NukeScriptProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: false
      Description: 'Builds a container to run AWS-Nuke for all accounts within the specified OU'
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/docker:18.09.0'
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_CONTEXT
            Type: PLAINTEXT
            Value: nuke
          - Name: BUILD_FILE
            Type: PLAINTEXT
            Value: ./codebuild.sh
          - Name: NUKE_PARENT
            Type: PLAINTEXT
            Value: ou-4z13-28regedd
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Sub 'AccountNuker-${AWS::StackName}'
          Status: ENABLED
      Name: !Sub 'AccountNuker-${AWS::StackName}'
      ServiceRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/NukeScriptProjectRole'
      Source:
        Location: 'https://github.com/leiarenee/aws-cloud-scripts.git'
        Type: GITHUB